title: Project

tabs:
  card:
    label: Project Card
    icon: grid-full
    columns: 
      - width: 1/2
        label: Front
        sections:
          front:
            type: fields
            fields:
              frontinfo:
                type: info
                label: false
                text: FRONT OF THE CARD
                align: center
                theme: none        
              fronttext:
                label: Title
                type: text
                required: true
              background:
                label: Background image
                type: files
                template: simple-image
                layout: list
                size: small
                max: 1
                image:
                  back: "#000"
                  icon: false
                  ratio: 1/1
                  cover: true
      - width: 1/2
        label: Back
        sections:
          back:
            type: fields
            fields:
              backinfo:
                type: info
                label: false
                text: BACK OF THE CARD
                align: center
                theme: none
              backtext:
                label: Short text
                type: textarea
                required: true
                buttons: false
                maxlength: 125
              pagestatus:
                label: Is the project page ready?
                type: toggle
                text: 
                  - "no"
                  - "yes"
              placeholder:
                label: Temporary text
                placeholder: More information soon
                help: If the project page is not ready, you can replace the link to the page with some text.
                type: text
                icon: text

  project:
    label: Project Page
    icon: page
    sections:
      parts:
        label: Page sections
        type: pages
        status: all
        info: "{{ page.intendedTemplate }}"
        image: false
        templates:
          - title-text
          - left-column-text
          - right-column-text
          - molds-images
          - gallery
          - cards