title: Project
options:
  changeSlug:
    admin: false
    editor: false
  navigation:
    status: listed
    template: all

tabs:
  project:
    label: Project Card
    icon: grid-full
    columns: 
      - width: 1/2
        label: Front
        sections:
          front:
            type: fields
            fields:
              frontinfo:
                type: info
                label: false
                text: FRONT OF THE CARD
                align: center
                theme: none        
              fronttext:
                label: Title
                type: textarea
              frontfooter:
                label: Footer
                type: text
                buttons: false
              background:
                label: Background image
                type: files
                template: simple-image
                layout: list
                size: small
                max: 1
                image:
                  back: "#000"
                  icon: false
                  ratio: 1/1
                  cover: true
      - width: 1/2
        label: Back
        sections:
          back:
            type: fields
            fields:
              backinfo:
                type: info
                label: false
                text: BACK OF THE CARD
                align: center
                theme: none
              backtext:
                label: Short text
                type: textarea
                maxlength: 125
                buttons: false
              backfooter:
                label: Footer
                type: text
              pagestatus:
                label: Is the project page ready?
                type: toggle
                text: 
                  - "no"
                  - "yes"
  page:
    label: Project Page
    icon: page
    sections:
      parts:
        label: Page sections
        type: pages
        status: all
        info: "{{ page.intendedTemplate }}"
        image: false
        templates:
          - title-text
          - left-column-text
          - right-column-text
          - one-column-text
          - two-columns-text
          - single-mold-image
          - gallery
          - cards
          - projects
          - logo-gallery