title: Site

sections:
  pages:
    type: pages
    label: "{{ page.title }}"
    image: false
    status: all
    template:
      - page
      - equipe
      - mediapage
      - home

  info:
    type: fields
    fields:
      settings:
        label: General Settings
        type: info
        theme: none
        text: Content fields below are global and available on all pages.
      address:
        label: Address
        type: textarea
        icon: map
        width: 1/3
        buttons: false
      email:
        label: Email
        type: email
        width: 1/3      
      temporarymenu:
        label: Temporary menu
        type: textarea
        width: 1/3
        buttons: false
      newslettername:
        label: Newsletter name
        type: text
        icon: bolt
        width: 1/3
        buttons: false
      newslettercta:
        label: Newsletter CTA
        type: textarea
        width: 1/3
        buttons: false
      partnerlink:
        label: Partner page
        type: text
        width: 1/3
        buttons: false

