title: Site

tabs:
  websitepages:
    label: Website Pages
    sections:
      pages:
        type: pages
        label: "{{ page.title }}"
        image: false
        status: all
        template:
          - page
          - equipe
          - mediapage
          - home
  general:
    label: Website Info
    sections:
      contact:
        type: fields
        fields:
          settings:
            label: false
            type: info
            theme: none
            text: Here you can control global information available on all pages.
          address:
            label: Address
            type: textarea
            width: 1/2
            buttons: false
          email:
            label: Email
            type: email
            width: 1/2
      newsletter:
        type: fields
        fields:
          newslettername:
            label: Newsletter name
            type: text
            width: 1/2
            buttons: false
          newslettercta:
            label: Newsletter call to action
            type: textarea
            width: 1/4
            buttons: false
          newsletterclick:
            label: false
            type: text
            width: 1/4
            buttons: false
      footer:
        type: fields
        fields:
          year:
            laberl: Year
            type: number
            width: 1/2
            after: '© least'
  websitemenu:
    label: Website Menu/Links
    sections:
      menu:
        type: fields
        fields:
          menulinks:
            label: false
            type: info
            theme: none
            text: Here you can control some names and labels used in links and menus.
          temporarymenu:
            label: Temporary menu
            type: textarea
            width: 1/2
            buttons: false
            help: When the field is empty, the actual menu will be shown.
          projects:
            label: Link to the projects section
            type: text
            width: 1/2
            help: Do you want the Projects to appear in the Home page menu?
            buttons: false
  seo:
    label: Website SEO
    sections:
      meta:
        type: fields
        fields: 
          description:
            label: Website description
            type: textarea
            width: 1/2
            buttons: false
          keywords:
            label: Website keywords
            type: tags
            separator: ','
            width: 1/2

