title: Site

tabs:
  websitepages:
    label: Website Pages
    sections:
      pages:
        type: pages
        label: "{{ page.title }}"
        image: false
        status: all
        template:
          - home
          - projects
          - mediapage
          - page
  general:
    label: Global Content
    sections:
      contact:
        type: fields
        fields:
          settings:
            label: false
            type: info
            theme: none
            text: Here you can control global information available on multiple pages.
          address:
            label: Address
            type: textarea
            width: 1/4
            buttons: false
          email:
            label: Email
            type: email
            width: 1/4
      newsletter:
        type: fields
        fields:
          newslettername:
            label: Newsletter
            type: text
            width: 1/4
            buttons: false
          newslettercta:
            label: false
            type: textarea
            width: 1/4
            buttons: false
          newsletterclick:
            label: false
            type: text
            width: 1/4
            buttons: false
            icon: angle-right
          newsletterlink:
            label: false
            type: text
            width: 1/4
            buttons: false
            icon: url
      footer:
        type: fields
        fields:
          year:
            laberl: Year
            type: number
            width: 1/4
            after: '© least'
  seo:
    label: Website SEO
    sections:
      meta:
        type: fields
        fields: 
          description:
            label: Website description
            type: textarea
            width: 1/2
            buttons: false
          keywords:
            label: Website keywords
            type: tags
            separator: ','
            width: 1/2

